package ch03;

public class A_Exception {

	public static void main(String[] args) {
		
		int number = 2;
		System.out.println(10 / number);
		
		System.out.println("나누기 연산이 실행되었습니다.");

	}

}
